version: '3.8'
services:
  simple_server:
    container_name: simpleserver-app
    ports:
      - 8484:8484
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: simple_server
    restart: unless-stopped
    networks:
      - simple-server-tier
    volumes:
      - ./simple_server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:4.4-bionic
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD:$MONGO_INITDB_ROOT_PASSWORD
    networks:
      - simple-server-tier
    volumes:
      - simple-server-data:/data/db
      
volumes:
  simple-server-data:
    driver: local

networks:
  simple-server-tier:
    driver: bridge
